var rawdata = [
  {
    "name": "Beta-i",
    "description": 0,
    "website": "http://beta-i.pt/",
    "city": "Lisboa",
    "country": "Portugal",
    "lon": -9.142385,
    "lat": 38.732435,
    "numa": "FALSE",
    "atalanta": "TRUE",
    "gfe": "FALSE",
    "gan": "FALSE"
  },
  {
    "name": "Tetuan Valley",
    "description": 0,
    "website": "http://tetuanvalley.com/",
    "city": "Madrid",
    "country": "Spain",
    "lon": -3.71806,
    "lat": 40.41216,
    "numa": "FALSE",
    "atalanta": "TRUE",
    "gfe": "FALSE",
    "gan": "FALSE"
  },
  {
    "name": "H-Farm",
    "description": 0,
    "website": "http://www.h-farm.com/",
    "city": "Venice",
    "country": "Italy",
    "lon": 12.427597,
    "lat": 45.564845,
    "numa": "FALSE",
    "atalanta": "TRUE",
    "gfe": "FALSE",
    "gan": "FALSE"
  },
  {
    "name": "Vocus UpStart",
    "description": 0,
    "website": "http://www.vocusupstart.com.au/",
    "city": "Cottesloe",
    "country": "Western Australia",
    "lon": 115.761735,
    "lat": -31.996453,
    "numa": "FALSE",
    "atalanta": "FALSE",
    "gfe": "FALSE",
    "gan": "TRUE"
  },
  {
    "name": "HubX",
    "description": 0,
    "website": "http://www.hubx.biz/",
    "city": "Little Rock",
    "country": "USA",
    "lon": -92.289595,
    "lat": 34.746481,
    "numa": "FALSE",
    "atalanta": "FALSE",
    "gfe": "FALSE",
    "gan": "TRUE"
  },
  {
    "name": "Straight Shot",
    "description": 0,
    "website": "http://straightshot.co/",
    "city": "Omaha",
    "country": "USA",
    "lon": -95.997988,
    "lat": 41.252363,
    "numa": "FALSE",
    "atalanta": "FALSE",
    "gfe": "FALSE",
    "gan": "TRUE"
  },
  {
    "name": "Blue Ridge Labs",
    "description": 0,
    "website": "https://labs.robinhood.org/",
    "city": "NYC",
    "country": "USA",
    "lon": -73.993003,
    "lat": 40.688901,
    "numa": "FALSE",
    "atalanta": "FALSE",
    "gfe": "FALSE",
    "gan": "TRUE"
  },
  {
    "name": "Seed Sumo",
    "description": 0,
    "website": "http://www.seedsumo.com/",
    "city": "College Station",
    "country": "USA",
    "lon": -96.382103,
    "lat": 30.599305,
    "numa": "FALSE",
    "atalanta": "FALSE",
    "gfe": "FALSE",
    "gan": "TRUE"
  },
  {
    "name": "Techstars London",
    "description": 0,
    "website": "http://www.techstars.com/apply/",
    "city": "London",
    "country": "UK",
    "lon": -0.05208,
    "lat": 51.520947,
    "numa": "FALSE",
    "atalanta": "FALSE",
    "gfe": "FALSE",
    "gan": "TRUE"
  },
  {
    "name": "Techstars Austin",
    "description": 0,
    "website": "http://www.techstars.com/apply/",
    "city": "Austin",
    "country": "USA",
    "lon": -97.745082,
    "lat": 30.266976,
    "numa": "FALSE",
    "atalanta": "FALSE",
    "gfe": "FALSE",
    "gan": "TRUE"
  },
  {
    "name": "StartupYard",
    "description": 0,
    "website": "http://startupyard.com/",
    "city": "Prague",
    "country": "Czech Republic",
    "lon": 14.402744,
    "lat": 50.066358,
    "numa": "FALSE",
    "atalanta": "FALSE",
    "gfe": "FALSE",
    "gan": "TRUE"
  },
  {
    "name": "Flat6labs",
    "description": 0,
    "website": "http://www.flat6labs.com/",
    "city": "Cairo",
    "country": "Egypt",
    "lon": 31.21215,
    "lat": 30.046231,
    "numa": "FALSE",
    "atalanta": "FALSE",
    "gfe": "FALSE",
    "gan": "TRUE"
  },
  {
    "name": "Gener8tor",
    "description": 0,
    "website": "http://www.gener8tor.com/",
    "city": "Milwaukee",
    "country": "USA",
    "lon": -87.911953,
    "lat": 43.034134,
    "numa": "FALSE",
    "atalanta": "FALSE",
    "gfe": "FALSE",
    "gan": "TRUE"
  },
  {
    "name": "Disney Accelerator, by Techstars",
    "description": 0,
    "website": "http://www.techstars.com/apply/",
    "city": "Los Angeles",
    "country": "USA",
    "lon": -118.243685,
    "lat": 34.052234,
    "numa": "FALSE",
    "atalanta": "FALSE",
    "gfe": "FALSE",
    "gan": "TRUE"
  },
  {
    "name": "Lightning Lab",
    "description": 0,
    "website": "http://www.lightninglab.co.nz/",
    "city": "Auckland",
    "country": "Australia/New Zealand",
    "lon": 174.758891,
    "lat": -36.866947,
    "numa": "FALSE",
    "atalanta": "FALSE",
    "gfe": "FALSE",
    "gan": "TRUE"
  },
  {
    "name": "Lightning Lab",
    "description": 0,
    "website": "http://www.lightninglab.co.nz/",
    "city": "Christchurch",
    "country": "Australia/New Zealand",
    "lon": 172.636225,
    "lat": -43.532054,
    "numa": "FALSE",
    "atalanta": "FALSE",
    "gfe": "FALSE",
    "gan": "TRUE"
  },
  {
    "name": "Lightning Lab",
    "description": 0,
    "website": "http://www.lightninglab.co.nz/",
    "city": "Wellington",
    "country": "Australia/New Zealand",
    "lon": 174.778383,
    "lat": -41.292409,
    "numa": "FALSE",
    "atalanta": "FALSE",
    "gfe": "FALSE",
    "gan": "TRUE"
  },
  {
    "name": "406labs",
    "description": 0,
    "website": "http://406labs.org/",
    "city": "Bozeman",
    "country": "USA",
    "lon": -111.042934,
    "lat": 45.676998,
    "numa": "FALSE",
    "atalanta": "FALSE",
    "gfe": "FALSE",
    "gan": "TRUE"
  },
  {
    "name": "AlphaLab",
    "description": 0,
    "website": "http://alphalab.org/",
    "city": "Pittsburgh",
    "country": "USA",
    "lon": -79.923472,
    "lat": 40.46206,
    "numa": "FALSE",
    "atalanta": "FALSE",
    "gfe": "FALSE",
    "gan": "TRUE"
  },
  {
    "name": "Boomtown",
    "description": 0,
    "website": "http://www.boomtownaccelerator.com/",
    "city": "Boulder",
    "country": "USA",
    "lon": -105.279993,
    "lat": 40.018689,
    "numa": "FALSE",
    "atalanta": "FALSE",
    "gfe": "FALSE",
    "gan": "TRUE"
  },
  {
    "name": "StartFast Venture Accelerator",
    "description": 0,
    "website": "http://startfast.net/",
    "city": "New York",
    "country": "USA",
    "lon": -76.149936,
    "lat": 43.044698,
    "numa": "FALSE",
    "atalanta": "FALSE",
    "gfe": "FALSE",
    "gan": "TRUE"
  },
  {
    "name": "Skystar Ventures",
    "description": 0,
    "website": "skystarventures.com",
    "city": "Jakarta",
    "country": "Indonesia",
    "lon": 106.616993,
    "lat": -6.257723,
    "numa": "FALSE",
    "atalanta": "FALSE",
    "gfe": "FALSE",
    "gan": "TRUE"
  },
  {
    "name": "The Brandery",
    "description": 0,
    "website": "http://brandery.org",
    "city": "Cincinnati",
    "country": "USA",
    "lon": -84.515707,
    "lat": 39.1109,
    "numa": "FALSE",
    "atalanta": "FALSE",
    "gfe": "FALSE",
    "gan": "TRUE"
  },
  {
    "name": "The Iron Yard",
    "description": 0,
    "website": "http://theironyard.com/",
    "city": "Greenville",
    "country": "USA",
    "lon": -82.399949,
    "lat": 34.851925,
    "numa": "FALSE",
    "atalanta": "FALSE",
    "gfe": "FALSE",
    "gan": "TRUE"
  },
  {
    "name": "Abc Accelerator",
    "description": 0,
    "website": "http://abc-accelerator.com/",
    "city": "Ljubljana",
    "country": "Slovenia",
    "lon": 14.548477,
    "lat": 46.069308,
    "numa": "FALSE",
    "atalanta": "FALSE",
    "gfe": "FALSE",
    "gan": "TRUE"
  },
  {
    "name": "Telluride Venture Accelerator",
    "description": 0,
    "website": "http://www.tellurideva.com/",
    "city": "Telluride",
    "country": "USA",
    "lon": -107.812285,
    "lat": 37.937494,
    "numa": "FALSE",
    "atalanta": "FALSE",
    "gfe": "FALSE",
    "gan": "TRUE"
  },
  {
    "name": "AREA",
    "description": 0,
    "website": "http://area.build/",
    "city": "New York",
    "country": "USA",
    "lon": -74.005941,
    "lat": 40.712784,
    "numa": "FALSE",
    "atalanta": "FALSE",
    "gfe": "FALSE",
    "gan": "TRUE"
  },
  {
    "name": "Microsoft Ventures Accelerator",
    "description": 0,
    "website": "https://www.microsoftventures.com/",
    "city": "Tel-Aviv",
    "country": "Israel",
    "lon": 34.781768,
    "lat": 32.0853,
    "numa": "FALSE",
    "atalanta": "FALSE",
    "gfe": "FALSE",
    "gan": "TRUE"
  },
  {
    "name": "Kaplan EdTech Accelerator",
    "description": 0,
    "website": "http://www.kaplanedtechaccelerator.com/",
    "city": "New York",
    "country": "USA",
    "lon": -74.005941,
    "lat": 40.712784,
    "numa": "FALSE",
    "atalanta": "FALSE",
    "gfe": "FALSE",
    "gan": "TRUE"
  },
  {
    "name": "LA Dodgers Accelerator",
    "description": 0,
    "website": "http://www.dodgersaccelerator.com/",
    "city": "Los Angeles",
    "country": "USA",
    "lon": -118.418152,
    "lat": 33.978542,
    "numa": "FALSE",
    "atalanta": "FALSE",
    "gfe": "FALSE",
    "gan": "TRUE"
  },
  {
    "name": "Startup Reykjavik",
    "description": 0,
    "website": "http://www.startupreykjavik.com/en",
    "city": "Reykjavik",
    "country": "Iceland",
    "lon": -21.901754,
    "lat": 64.145797,
    "numa": "FALSE",
    "atalanta": "FALSE",
    "gfe": "FALSE",
    "gan": "TRUE"
  },
  {
    "name": "BoomStartup",
    "description": 0,
    "website": "http://boomstartup.com/about-us/contact-us/",
    "city": "Salt Lake City",
    "country": "USA",
    "lon": -111.883687,
    "lat": 40.756939,
    "numa": "FALSE",
    "atalanta": "FALSE",
    "gfe": "FALSE",
    "gan": "TRUE"
  },
  {
    "name": "BoomStartup",
    "description": 0,
    "website": "http://boomstartup.com/about-us/contact-us/",
    "city": "Park City",
    "country": "USA",
    "lon": -111.562805,
    "lat": 40.748025,
    "numa": "FALSE",
    "atalanta": "FALSE",
    "gfe": "FALSE",
    "gan": "TRUE"
  },
  {
    "name": "BoomStartup",
    "description": 0,
    "website": "http://boomstartup.com/about-us/contact-us/",
    "city": "Lehi",
    "country": "USA",
    "lon": -111.660947,
    "lat": 40.226209,
    "numa": "FALSE",
    "atalanta": "FALSE",
    "gfe": "FALSE",
    "gan": "TRUE"
  },
  {
    "name": "SecureSet",
    "description": 0,
    "website": "https://www.secureset.com/accelerator/",
    "city": "Denver",
    "country": "USA",
    "lon": -104.968687,
    "lat": 39.770204,
    "numa": "FALSE",
    "atalanta": "FALSE",
    "gfe": "FALSE",
    "gan": "TRUE"
  },
  {
    "name": "Techstars in Seattle",
    "description": 0,
    "website": "http://www.techstars.com/apply/",
    "city": "Seattle",
    "country": "USA",
    "lon": -122.332071,
    "lat": 47.606209,
    "numa": "FALSE",
    "atalanta": "FALSE",
    "gfe": "FALSE",
    "gan": "TRUE"
  },
  {
    "name": "Top Seeds Lab",
    "description": 0,
    "website": "http://www.topseedslab.com/en/",
    "city": "Madrid",
    "country": "Spain",
    "lon": -3.70379,
    "lat": 40.416775,
    "numa": "FALSE",
    "atalanta": "FALSE",
    "gfe": "FALSE",
    "gan": "TRUE"
  },
  {
    "name": "Ideaboost",
    "description": 0,
    "website": "http://www.ideaboost.ca/",
    "city": "Toronto",
    "country": "Canada",
    "lon": -79.383184,
    "lat": 43.653226,
    "numa": "FALSE",
    "atalanta": "FALSE",
    "gfe": "FALSE",
    "gan": "TRUE"
  },
  {
    "name": "Alphalab Gear",
    "description": 0,
    "website": "http://alphalab.org/",
    "city": "Pittsburgh",
    "country": "USA",
    "lon": -79.995886,
    "lat": 40.440625,
    "numa": "FALSE",
    "atalanta": "FALSE",
    "gfe": "FALSE",
    "gan": "TRUE"
  },
  {
    "name": "Chinaccelerator",
    "description": 0,
    "website": "http://chinaccelerator.com/",
    "city": "Shanghai",
    "country": "China",
    "lon": 121.473701,
    "lat": 31.230416,
    "numa": "FALSE",
    "atalanta": "FALSE",
    "gfe": "FALSE",
    "gan": "TRUE"
  },
  {
    "name": "Techstars in NYC",
    "description": 0,
    "website": "http://www.techstars.com/apply/",
    "city": "New York",
    "country": "USA",
    "lon": -74.005941,
    "lat": 40.712784,
    "numa": "FALSE",
    "atalanta": "FALSE",
    "gfe": "FALSE",
    "gan": "TRUE"
  },
  {
    "name": "Flat6labs",
    "description": 0,
    "website": "http://www.flat6labsjeddah.com/",
    "city": "Jeddah",
    "country": "Saudi Arabia",
    "lon": 39.237551,
    "lat": 21.285407,
    "numa": "FALSE",
    "atalanta": "FALSE",
    "gfe": "FALSE",
    "gan": "TRUE"
  },
  {
    "name": "Techstars Clouf",
    "description": 0,
    "website": "http://www.techstars.com/apply/",
    "city": "San Antonio",
    "country": "USA",
    "lon": -98.493628,
    "lat": 29.424122,
    "numa": "FALSE",
    "atalanta": "FALSE",
    "gfe": "FALSE",
    "gan": "TRUE"
  },
  {
    "name": "Capital Innovators",
    "description": 0,
    "website": "http://capitalinnovators.com/",
    "city": "St. Louis",
    "country": "USA",
    "lon": -90.199404,
    "lat": 38.627003,
    "numa": "FALSE",
    "atalanta": "FALSE",
    "gfe": "FALSE",
    "gan": "TRUE"
  },
  {
    "name": "Coolhouse labs",
    "description": 0,
    "website": "http://coolhouselabs.com/",
    "city": "Harbor Spirngs",
    "country": "USA",
    "lon": -84.991999,
    "lat": 45.431676,
    "numa": "FALSE",
    "atalanta": "FALSE",
    "gfe": "FALSE",
    "gan": "TRUE"
  },
  {
    "name": "Summer Institute",
    "description": 0,
    "website": "http://www.summerinst.ca/",
    "city": "New Brunswick",
    "country": "Canada",
    "lon": -66.641801,
    "lat": 45.949346,
    "numa": "FALSE",
    "atalanta": "FALSE",
    "gfe": "FALSE",
    "gan": "TRUE"
  },
  {
    "name": "DAI Accelerator",
    "description": 0,
    "website": "http://%20dai.com/",
    "city": "Bethesda",
    "country": "USA",
    "lon": -77.094709,
    "lat": 38.984652,
    "numa": "FALSE",
    "atalanta": "FALSE",
    "gfe": "FALSE",
    "gan": "TRUE"
  },
  {
    "name": "Techstars in Boston",
    "description": 0,
    "website": "http://www.techstars.com/apply/",
    "city": "Boston",
    "country": "USA",
    "lon": -71.05888,
    "lat": 42.360082,
    "numa": "FALSE",
    "atalanta": "FALSE",
    "gfe": "FALSE",
    "gan": "TRUE"
  },
  {
    "name": "Velocity",
    "description": 0,
    "website": "http://www.innovationdepot.org/",
    "city": "Birmingham",
    "country": "USA",
    "lon": -86.80249,
    "lat": 33.520661,
    "numa": "FALSE",
    "atalanta": "FALSE",
    "gfe": "FALSE",
    "gan": "TRUE"
  },
  {
    "name": "Lighthouse Labs",
    "description": 0,
    "website": "http://www.lighthouselabsrva.com/",
    "city": "Richmond",
    "country": "USA",
    "lon": -77.436048,
    "lat": 37.540725,
    "numa": "FALSE",
    "atalanta": "FALSE",
    "gfe": "FALSE",
    "gan": "TRUE"
  },
  {
    "name": "Better ventures",
    "description": 0,
    "website": "http://www.better.vc/",
    "city": "San Francisco",
    "country": "USA",
    "lon": -122.419416,
    "lat": 37.774929,
    "numa": "FALSE",
    "atalanta": "FALSE",
    "gfe": "FALSE",
    "gan": "TRUE"
  },
  {
    "name": "STING",
    "description": 0,
    "website": "http://www.stockholminnovation.com/en/our-programs/sting-accelerate/",
    "city": "Stockholm",
    "country": "Sweden",
    "lon": 18.068581,
    "lat": 59.329323,
    "numa": "FALSE",
    "atalanta": "FALSE",
    "gfe": "FALSE",
    "gan": "TRUE"
  },
  {
    "name": "Techstars",
    "description": 0,
    "website": "http://www.techstars.com/apply/",
    "city": "Boulder",
    "country": "USA",
    "lon": -105.270546,
    "lat": 40.014986,
    "numa": "FALSE",
    "atalanta": "FALSE",
    "gfe": "FALSE",
    "gan": "TRUE"
  },
  {
    "name": "Mucker Lab",
    "description": 0,
    "website": "http://www.muckerlab.com/",
    "city": "Santa Monica",
    "country": "USA",
    "lon": -118.491191,
    "lat": 34.019454,
    "numa": "FALSE",
    "atalanta": "FALSE",
    "gfe": "FALSE",
    "gan": "TRUE"
  },
  {
    "name": "UTEC Ventures",
    "description": 0,
    "website": "http://www.utecventures.com/",
    "city": "Lima",
    "country": "Peru",
    "lon": -77.042793,
    "lat": -12.046374,
    "numa": "FALSE",
    "atalanta": "FALSE",
    "gfe": "FALSE",
    "gan": "TRUE"
  },
  {
    "name": "Luiss Enlabs",
    "description": 0,
    "website": "http://luissenlabs.com/",
    "city": "Rome",
    "country": "Italy",
    "lon": 12.496366,
    "lat": 41.902783,
    "numa": "FALSE",
    "atalanta": "FALSE",
    "gfe": "FALSE",
    "gan": "TRUE"
  },
  {
    "name": "Start Co",
    "description": 0,
    "website": "http://neverstop.co/",
    "city": "Menphis",
    "country": "USA",
    "lon": -90.04898,
    "lat": 35.149534,
    "numa": "FALSE",
    "atalanta": "FALSE",
    "gfe": "FALSE",
    "gan": "TRUE"
  },
  {
    "name": "JFDI",
    "description": 0,
    "website": "http://www.jfdi.asia/",
    "city": "Singapore",
    "country": "Singapore",
    "lon": 103.819836,
    "lat": 1.352083,
    "numa": "FALSE",
    "atalanta": "FALSE",
    "gfe": "FALSE",
    "gan": "TRUE"
  },
  {
    "name": "Sparklabs",
    "description": 0,
    "website": "http://www.sparklabs.co.kr/",
    "city": "Seoul",
    "country": "South Korea",
    "lon": 126.977969,
    "lat": 37.566535,
    "numa": "FALSE",
    "atalanta": "FALSE",
    "gfe": "FALSE",
    "gan": "TRUE"
  },
  {
    "name": "NXTP Labs",
    "description": 0,
    "website": "http://www.nxtplabs.com/",
    "city": "Buenos Aires",
    "country": "Argentina",
    "lon": -58.381559,
    "lat": -34.603684,
    "numa": "FALSE",
    "atalanta": "FALSE",
    "gfe": "FALSE",
    "gan": "TRUE"
  },
  {
    "name": "Spring Mobile Health Accelerator, by Techstars",
    "description": 0,
    "website": "http://www.techstars.com/apply/",
    "city": "Kansas City",
    "country": "USA",
    "lon": -94.578567,
    "lat": 39.099727,
    "numa": "FALSE",
    "atalanta": "FALSE",
    "gfe": "FALSE",
    "gan": "TRUE"
  },
  {
    "name": "Jumpstart Foundry",
    "description": 0,
    "website": "http://www.jsf.co/",
    "city": "Nashville",
    "country": "USA",
    "lon": -86.781602,
    "lat": 36.162664,
    "numa": "FALSE",
    "atalanta": "FALSE",
    "gfe": "FALSE",
    "gan": "TRUE"
  },
  {
    "name": "Eleven",
    "description": 0,
    "website": "http://11.me/",
    "city": "Sofia",
    "country": "Bulgaria",
    "lon": 23.321868,
    "lat": 42.697708,
    "numa": "FALSE",
    "atalanta": "FALSE",
    "gfe": "FALSE",
    "gan": "TRUE"
  },
  {
    "name": "Start Planet",
    "description": 0,
    "website": "http://www.startplanetni.com/",
    "city": "Belfast",
    "country": "Ireland",
    "lon": -5.93012,
    "lat": 54.597285,
    "numa": "FALSE",
    "atalanta": "FALSE",
    "gfe": "FALSE",
    "gan": "TRUE"
  },
  {
    "name": "Elmspring Accelerator",
    "description": 0,
    "website": "http://www.elmspringaccelerator.com/",
    "city": "Chicago",
    "country": "USA",
    "lon": -87.629798,
    "lat": 41.878114,
    "numa": "FALSE",
    "atalanta": "FALSE",
    "gfe": "FALSE",
    "gan": "TRUE"
  },
  {
    "name": "R/GA Connected Devices Accelerator, by Techstars",
    "description": 0,
    "website": "http://rgaaccelerator.com/connecteddevices/",
    "city": "NYC",
    "country": "USA",
    "lon": -74.005941,
    "lat": 40.712784,
    "numa": "FALSE",
    "atalanta": "FALSE",
    "gfe": "FALSE",
    "gan": "TRUE"
  },
  {
    "name": "Startup Bootcamp",
    "description": 0,
    "website": "http://startupbootcamp.org/",
    "city": "Amsterdam",
    "country": "Netherlands",
    "lon": 4.895168,
    "lat": 52.370216,
    "numa": "FALSE",
    "atalanta": "FALSE",
    "gfe": "FALSE",
    "gan": "TRUE"
  },
  {
    "name": "Startup Bootcamp",
    "description": 0,
    "website": "http://startupbootcamp.org/",
    "city": "Barcelona",
    "country": "Spain",
    "lon": 2.173403,
    "lat": 41.385064,
    "numa": "FALSE",
    "atalanta": "FALSE",
    "gfe": "FALSE",
    "gan": "TRUE"
  },
  {
    "name": "Startup Bootcamp",
    "description": 0,
    "website": "http://startupbootcamp.org/",
    "city": "Berlin",
    "country": "Germany",
    "lon": 13.404954,
    "lat": 52.520007,
    "numa": "FALSE",
    "atalanta": "FALSE",
    "gfe": "FALSE",
    "gan": "TRUE"
  },
  {
    "name": "Startup Bootcamp",
    "description": 0,
    "website": "http://startupbootcamp.org/",
    "city": "Copenhagen",
    "country": "Danmark",
    "lon": 12.568337,
    "lat": 55.676097,
    "numa": "FALSE",
    "atalanta": "FALSE",
    "gfe": "FALSE",
    "gan": "TRUE"
  },
  {
    "name": "Startup Bootcamp",
    "description": 0,
    "website": "http://startupbootcamp.org/",
    "city": "Eindhoven",
    "country": "Netherlands",
    "lon": 5.469722,
    "lat": 51.441642,
    "numa": "FALSE",
    "atalanta": "FALSE",
    "gfe": "FALSE",
    "gan": "TRUE"
  },
  {
    "name": "Startup Bootcamp",
    "description": 0,
    "website": "http://startupbootcamp.org/",
    "city": "Istanbul",
    "country": "Turkey",
    "lon": 28.978359,
    "lat": 41.008238,
    "numa": "FALSE",
    "atalanta": "FALSE",
    "gfe": "FALSE",
    "gan": "TRUE"
  },
  {
    "name": "Startup Bootcamp",
    "description": 0,
    "website": "http://startupbootcamp.org/",
    "city": "London",
    "country": "UK",
    "lon": -0.127758,
    "lat": 51.507351,
    "numa": "FALSE",
    "atalanta": "FALSE",
    "gfe": "FALSE",
    "gan": "TRUE"
  },
  {
    "name": "Startup Bootcamp",
    "description": 0,
    "website": "http://startupbootcamp.org/",
    "city": "Miami",
    "country": "USA",
    "lon": -80.19179,
    "lat": 25.76168,
    "numa": "FALSE",
    "atalanta": "FALSE",
    "gfe": "FALSE",
    "gan": "TRUE"
  },
  {
    "name": "Startup Bootcamp",
    "description": 0,
    "website": "http://startupbootcamp.org/",
    "city": "New York",
    "country": "USA",
    "lon": -74.005941,
    "lat": 40.712784,
    "numa": "FALSE",
    "atalanta": "FALSE",
    "gfe": "FALSE",
    "gan": "TRUE"
  },
  {
    "name": "Startup Bootcamp",
    "description": 0,
    "website": "http://startupbootcamp.org/",
    "city": "Rome",
    "country": "Italy",
    "lon": 12.496366,
    "lat": 41.902783,
    "numa": "FALSE",
    "atalanta": "FALSE",
    "gfe": "FALSE",
    "gan": "TRUE"
  },
  {
    "name": "Startup Bootcamp",
    "description": 0,
    "website": "http://startupbootcamp.org/",
    "city": "Singapore",
    "country": "Singapore",
    "lon": 103.819836,
    "lat": 1.352083,
    "numa": "FALSE",
    "atalanta": "FALSE",
    "gfe": "FALSE",
    "gan": "TRUE"
  },
  {
    "name": "Desai Accelerator",
    "description": 0,
    "website": "http://%20desaiaccelerator.umich.edu/",
    "city": "Ann Arbor",
    "country": "USA",
    "lon": -83.743038,
    "lat": 42.280826,
    "numa": "FALSE",
    "atalanta": "FALSE",
    "gfe": "FALSE",
    "gan": "TRUE"
  },
  {
    "name": "Blue Startups",
    "description": 0,
    "website": "http://www.bluestartups.com/",
    "city": "Honolulu",
    "country": "Hawaii",
    "lon": -157.858333,
    "lat": 21.306944,
    "numa": "FALSE",
    "atalanta": "FALSE",
    "gfe": "FALSE",
    "gan": "TRUE"
  },
  {
    "name": "Techstars in Chicago",
    "description": 0,
    "website": "http://www.techstars.com/",
    "city": "Chicago",
    "country": "USA",
    "lon": -87.629798,
    "lat": 41.878114,
    "numa": "FALSE",
    "atalanta": "FALSE",
    "gfe": "FALSE",
    "gan": "TRUE"
  },
  {
    "name": "01Booster",
    "description": 0,
    "website": "http://01booster.com/english",
    "city": "Tokyo",
    "country": "Japan",
    "lon": 139.691706,
    "lat": 35.689487,
    "numa": "FALSE",
    "atalanta": "FALSE",
    "gfe": "FALSE",
    "gan": "TRUE"
  },
  {
    "name": "AeroInnovate",
    "description": 0,
    "website": "http://www.aeroinnovate.org/",
    "city": "Oshkosh",
    "country": "USA",
    "lon": -88.542614,
    "lat": 44.024706,
    "numa": "FALSE",
    "atalanta": "FALSE",
    "gfe": "FALSE",
    "gan": "TRUE"
  },
  {
    "name": "NMotion",
    "description": 0,
    "website": "http://www.nmotion.co/",
    "city": "Lincoln",
    "country": "USA",
    "lon": -96.685198,
    "lat": 40.825763,
    "numa": "FALSE",
    "atalanta": "FALSE",
    "gfe": "FALSE",
    "gan": "TRUE"
  },
  {
    "name": "American Underground",
    "description": 0,
    "website": "http://americanunderground.com/",
    "city": "Raleigh-Durham",
    "country": "USA",
    "lon": -78.638179,
    "lat": 30.267153,
    "numa": "FALSE",
    "atalanta": "FALSE",
    "gfe": "TRUE",
    "gan": "FALSE"
  },
  {
    "name": "The Capital Factory",
    "description": 0,
    "website": "https://capitalfactory.com/",
    "city": "Austin",
    "country": "USA",
    "lon": -97.743061,
    "lat": 30.267153,
    "numa": "FALSE",
    "atalanta": "FALSE",
    "gfe": "TRUE",
    "gan": "FALSE"
  },
  {
    "name": "The Entrepreneur Center",
    "description": 0,
    "website": "http://www.ec.co/",
    "city": "Nashville",
    "country": "USA",
    "lon": -86.781602,
    "lat": 36.162664,
    "numa": "FALSE",
    "atalanta": "FALSE",
    "gfe": "TRUE",
    "gan": "FALSE"
  },
  {
    "name": "COCO",
    "description": 0,
    "website": "https://explorecoco.com/",
    "city": "Minneapolis",
    "country": "USA",
    "lon": -93.265011,
    "lat": 44.977753,
    "numa": "FALSE",
    "atalanta": "FALSE",
    "gfe": "TRUE",
    "gan": "FALSE"
  },
  {
    "name": "Communitech",
    "description": 0,
    "website": "https://www.communitech.ca/",
    "city": "Waterloo",
    "country": "Canada",
    "lon": -80.52041,
    "lat": 43.464258,
    "numa": "FALSE",
    "atalanta": "FALSE",
    "gfe": "TRUE",
    "gan": "FALSE"
  },
  {
    "name": "Galvanize",
    "description": 0,
    "website": "http://www.galvanize.com/#welcome",
    "city": "Denver",
    "country": "USA",
    "lon": -104.990251,
    "lat": 39.739236,
    "numa": "FALSE",
    "atalanta": "FALSE",
    "gfe": "TRUE",
    "gan": "FALSE"
  },
  {
    "name": "Grand Circus",
    "description": 0,
    "website": "http://www.grandcircus.co/",
    "city": "Detroit",
    "country": "USA",
    "lon": -83.045754,
    "lat": 42.331427,
    "numa": "FALSE",
    "atalanta": "FALSE",
    "gfe": "TRUE",
    "gan": "FALSE"
  },
  {
    "name": "Notman House",
    "description": 0,
    "website": "http://notman.org/",
    "city": "Montreal",
    "country": "Canada",
    "lon": -73.567256,
    "lat": 45.501689,
    "numa": "FALSE",
    "atalanta": "FALSE",
    "gfe": "TRUE",
    "gan": "FALSE"
  },
  {
    "name": 1871,
    "description": 0,
    "website": "http://www.1871.com/",
    "city": "Chicago",
    "country": "USA",
    "lon": -87.629798,
    "lat": 41.878114,
    "numa": "FALSE",
    "atalanta": "FALSE",
    "gfe": "TRUE",
    "gan": "FALSE"
  },
  {
    "name": "Centraal",
    "description": 0,
    "website": "http://centraal.com/",
    "city": "Mexico City",
    "country": "Mexico",
    "lon": -99.133208,
    "lat": 19.432608,
    "numa": "FALSE",
    "atalanta": "FALSE",
    "gfe": "TRUE",
    "gan": "FALSE"
  },
  {
    "name": "ccHub",
    "description": 0,
    "website": "http://cchubnigeria.com/",
    "city": "Lagos",
    "country": "Nigeria",
    "lon": 3.379206,
    "lat": 6.524379,
    "numa": "FALSE",
    "atalanta": "FALSE",
    "gfe": "TRUE",
    "gan": "FALSE"
  },
  {
    "name": "Jozihub",
    "description": 0,
    "website": "http://jozihub.org/",
    "city": "Johannesburg",
    "country": "South Africa",
    "lon": 28.047305,
    "lat": -26.204103,
    "numa": "FALSE",
    "atalanta": "FALSE",
    "gfe": "TRUE",
    "gan": "FALSE"
  },
  {
    "name": "iHub",
    "description": 0,
    "website": "http://www.ihub.co.ke/",
    "city": "Nairobi",
    "country": "Kenya",
    "lon": 36.821946,
    "lat": -1.292066,
    "numa": "FALSE",
    "atalanta": "FALSE",
    "gfe": "TRUE",
    "gan": "FALSE"
  },
  {
    "name": "iSpaces",
    "description": 0,
    "website": "http://ispacegh.com/",
    "city": "Accra",
    "country": "Ghana",
    "lon": -0.186964,
    "lat": 5.603717,
    "numa": "FALSE",
    "atalanta": "FALSE",
    "gfe": "TRUE",
    "gan": "FALSE"
  },
  {
    "name": "Outbox",
    "description": 0,
    "website": "http://www.outbox.co.ug/",
    "city": "Kampala",
    "country": "Uganda",
    "lon": 32.58252,
    "lat": 0.347596,
    "numa": "FALSE",
    "atalanta": "FALSE",
    "gfe": "TRUE",
    "gan": "FALSE"
  },
  {
    "name": "Factory",
    "description": 0,
    "website": "http://www.factoryberlin.com/",
    "city": "Berlin",
    "country": "Germany",
    "lon": 13.404954,
    "lat": 52.520007,
    "numa": "FALSE",
    "atalanta": "FALSE",
    "gfe": "TRUE",
    "gan": "FALSE"
  },
  {
    "name": "Epicenter",
    "description": 0,
    "website": "https://epicenterstockholm.com/en/gfe",
    "city": "Stockholm",
    "country": "Sweden",
    "lon": 18.068581,
    "lat": 59.329323,
    "numa": "FALSE",
    "atalanta": "FALSE",
    "gfe": "TRUE",
    "gan": "FALSE"
  },
  {
    "name": "Dogpatchlabs",
    "description": 0,
    "website": "http://dogpatchlabs.com/",
    "city": "Dublin",
    "country": "Ireland",
    "lon": -6.26031,
    "lat": 53.349805,
    "numa": "FALSE",
    "atalanta": "FALSE",
    "gfe": "TRUE",
    "gan": "FALSE"
  },
  {
    "name": "Fishburners",
    "description": 0,
    "website": "http://fishburners.org/",
    "city": "Sydney",
    "country": "Australia",
    "lon": 151.20699,
    "lat": -33.867487,
    "numa": "FALSE",
    "atalanta": "FALSE",
    "gfe": "TRUE",
    "gan": "FALSE"
  },
  {
    "name": "Manos Accelerator",
    "description": 0,
    "website": "http://www.manosaccelerator.com/",
    "city": "San Jose",
    "country": "USA",
    "lon": -121.886329,
    "lat": 37.338208,
    "numa": "FALSE",
    "atalanta": "FALSE",
    "gfe": "TRUE",
    "gan": "FALSE"
  },
  {
    "name": "Maru180",
    "description": 0,
    "website": "http://maru180.com/pcindex.php",
    "city": "Seoul",
    "country": "Korea",
    "lon": 126.977969,
    "lat": 37.566535,
    "numa": "FALSE",
    "atalanta": "FALSE",
    "gfe": "TRUE",
    "gan": "FALSE"
  },
  {
    "name": "10000 Startups",
    "description": 0,
    "website": "http://10000startups.com/",
    "city": "Bangalore",
    "country": "India",
    "lon": 77.594563,
    "lat": 12.971599,
    "numa": "FALSE",
    "atalanta": "FALSE",
    "gfe": "TRUE",
    "gan": "FALSE"
  },
  {
    "name": "The Nest",
    "description": 0,
    "website": "http://thenestio.com/",
    "city": "Karachi",
    "country": "Pakistan",
    "lon": 67.009939,
    "lat": 24.861462,
    "numa": "FALSE",
    "atalanta": "FALSE",
    "gfe": "TRUE",
    "gan": "FALSE"
  },
  {
    "name": "Astrolabs",
    "description": 0,
    "website": "http://astrolabs.com/",
    "city": "Dubai",
    "country": "United Arab Emirates",
    "lon": 55.270783,
    "lat": 25.204849,
    "numa": "FALSE",
    "atalanta": "FALSE",
    "gfe": "TRUE",
    "gan": "FALSE"
  },
  {
    "name": "Gaza Sky Geeks",
    "description": 0,
    "website": "http://www.gazaskygeeks.com/",
    "city": "Gaza",
    "country": "Gaza",
    "lon": 34.466844,
    "lat": 31.501695,
    "numa": "FALSE",
    "atalanta": "FALSE",
    "gfe": "TRUE",
    "gan": "FALSE"
  },
  {
    "name": "Code2040",
    "description": 0,
    "website": "http://www.code2040.org/",
    "city": "Chicago",
    "country": "USA",
    "lon": -87.629798,
    "lat": 41.878114,
    "numa": "FALSE",
    "atalanta": "FALSE",
    "gfe": "TRUE",
    "gan": "FALSE"
  },
  {
    "name": "Campus Tel Aviv",
    "description": 0,
    "website": "https://www.campus.co/tel-aviv/en",
    "city": "Tel Aviv",
    "country": "Israel",
    "lon": 34.794145,
    "lat": 32.07008,
    "numa": "FALSE",
    "atalanta": "FALSE",
    "gfe": "TRUE",
    "gan": "FALSE"
  },
  {
    "name": "Campus London",
    "description": 0,
    "website": "https://www.campus.co/london/en",
    "city": "London",
    "country": "UK",
    "lon": -0.085515,
    "lat": 51.5226,
    "numa": "FALSE",
    "atalanta": "FALSE",
    "gfe": "TRUE",
    "gan": "FALSE"
  },
  {
    "name": "Campus Seoul",
    "description": 0,
    "website": "https://www.campus.co/seoul/ko",
    "city": "Seoul",
    "country": "Korea",
    "lon": 127.063485,
    "lat": 37.506053,
    "numa": "FALSE",
    "atalanta": "FALSE",
    "gfe": "TRUE",
    "gan": "FALSE"
  },
  {
    "name": "Campus Madrid",
    "description": 0,
    "website": "https://www.campus.co/madrid/en",
    "city": "Madrid",
    "country": "Spain",
    "lon": -3.718322,
    "lat": 40.412633,
    "numa": "FALSE",
    "atalanta": "FALSE",
    "gfe": "TRUE",
    "gan": "FALSE"
  },
  {
    "name": "Campus Warsaw",
    "description": 0,
    "website": "https://www.campus.co/warsaw/en",
    "city": "Warsaw",
    "country": "Poland",
    "lon": 21.044536,
    "lat": 52.254909,
    "numa": "FALSE",
    "atalanta": "FALSE",
    "gfe": "TRUE",
    "gan": "FALSE"
  },
  {
    "name": "Campus Sao Paulo",
    "description": 0,
    "website": "https://www.campus.co/sao-paulo/en",
    "city": "Sao Paulo",
    "country": "Brazil",
    "lon": -46.649886,
    "lat": -23.570991,
    "numa": "FALSE",
    "atalanta": "FALSE",
    "gfe": "TRUE",
    "gan": "FALSE"
  },
  {
    "name": "NUMA",
    "description": 0,
    "website": "http://numa.co",
    "city": "Paris",
    "country": "France",
    "lon": 2.34954,
    "lat": 48.86763,
    "numa": "TRUE",
    "atalanta": "FALSE",
    "gfe": "FALSE",
    "gan": "FALSE"
  },
  {
    "name": "NUMA Moscow",
    "description": 0,
    "website": "http://numa.co",
    "city": "Moscow",
    "country": "Russia",
    "lon": 37.645531,
    "lat": 55.726055,
    "numa": "TRUE",
    "atalanta": "FALSE",
    "gfe": "FALSE",
    "gan": "FALSE"
  },
  {
    "name": "NUMA Bengaluru",
    "description": 0,
    "website": "http://numa.co",
    "city": "Bengaluru",
    "country": "India",
    "lon": 77.599271,
    "lat": 12.976594,
    "numa": "TRUE",
    "atalanta": "FALSE",
    "gfe": "FALSE",
    "gan": "FALSE"
  },
  {
    "name": "NUMA Casablanca",
    "description": 0,
    "website": "http://numa.co",
    "city": "Casablanca",
    "country": "Morroco",
    "lon": -7.635305,
    "lat": 33.548591,
    "numa": "TRUE",
    "atalanta": "FALSE",
    "gfe": "FALSE",
    "gan": "FALSE"
  },
  {
    "name": "NUMA Barcelona",
    "description": 0,
    "website": "http://numa.co",
    "city": "Barcelona",
    "country": "Spain",
    "lon": 2.185167,
    "lat": 41.381992,
    "numa": "TRUE",
    "atalanta": "FALSE",
    "gfe": "FALSE",
    "gan": "FALSE"
  },
  {
    "name": "NUMA Mexico",
    "description": 0,
    "website": "http://numa.co",
    "city": "Mexico City",
    "country": "Mexico",
    "lon": -99.168771,
    "lat": 19.40881,
    "numa": "TRUE",
    "atalanta": "FALSE",
    "gfe": "FALSE",
    "gan": "FALSE"
  }
];




function getGeoJson({name, website, city, country, lon, lat, numa, gfe, atalanta, gan}) {

    var isNUMA = numa === 'TRUE';
    var isAtalanta = atalanta === 'TRUE';
    var isGFE = gfe === 'TRUE';
    var isGAN = gan === 'TRUE';

    // var colors = {
    //     roseFushia: "#E50064",
    //     roseCandy: "#E94190",
    //     bleuKlein:"#302683",
    //     turquoise: "#1CABBB",
    //     jaune: "#FFF489",
    //     ardoise: "#00587D",
    //     celadon: "#8AC5C6",
    //     raisin: "#731A66",
    //     sable: "#FEE9C9",
    //     mandarine: "#F7AA59",
    // }

    // var color;
    // if(isNUMA){
    //     color = colors.roseFushia;
    // } else if (isGFE){
    //     color = colors.ardoise;
    // } else if (isAtalanta){
    //     color = colors.raisin;
    // } else if (isGAN) {
    //     color = colors.bleuKlein;
    // }


    
    var geojson = {
      "type": "Feature",
      "geometry": {
        "coordinates": [
          lon,
          lat
        ],
        "type": "Point"
      },
      "properties": {
        "name": name,
        "website": website,
        "city": city,
        "country": country,
        "NUMA": isNUMA,
        "GFE": isGFE,
        "ATALANTA": isAtalanta,
        "GAN": isGAN,
        //"marker-color": color,
        //"marker-size": "large",
        //"marker-symbol": "rocket"
      }
    }

    return geojson; 
};



var mapdata = rawdata.map(getGeoJson);




